
ALTER TABLE public.deliveries
  ADD COLUMN IF NOT EXISTS formatted_address TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS lat DOUBLE PRECISION DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS lng DOUBLE PRECISION DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS completed_at TIMESTAMP WITH TIME ZONE DEFAULT NULL;

ALTER PUBLICATION supabase_realtime ADD TABLE public.deliveries;
